### ISSUE TITLE
Working with polyploid input

### ISSUE THREAD

**Issue by photocyte** [pjedge/hapcut2#13]
Hi there,

Does HapCut2 work with polyploid samples and/or is there a parameter to specify ploidy greater than 2?  My use case is a set of high coverage (>1000+) mitochondrial genomes from 4 pooled individuals (4+ haplotypes), with PacBio RSII data.

Best,
-Tim

**Comment by pjedge** [comment]
Hi Tim,

Unfortunately it does not. The only haplotype assembly tool I know of that supports polyploid samples is HapTree.
