### ISSUE TITLE
Haplotype output format for HAPCUT2

### ISSUE THREAD

**Issue by nh13** [pjedge/hapcut2#2]
@pjedge thanks for your help in advance.

The output format of `HAPCUT` previously hapcut-specific genotype-level information (from `printhaplotypes.c`):

```
// print genotype read counts and likelihoods
if (snpfrag[t].G00 < 0 || snpfrag[t].G01 < 0 || snpfrag[t].G11 < 0)fprintf(fp,"\t%d,%d:%0.1f,%0.1f,%0.1f\n",snpfrag[t].A0,snpfrag[t].A1,snpfrag[t].G00,snpfrag[t].G01,snpfrag[t].G11);
else fprintf(fp,"\n");
```

My own interpretation of this data is:

```
  //  R0,R1:L00,L01,L11:delta:rMEC
  //  "%d,%d:%0.1f,%0.1f,%0.1f:%0.1f:%0.1f"
  //  R0,R1: counts of calls supporting allele0 and allele1 respectively
  //  L00,L01,L11: change in likelihood if this SNP is made homozygous or removed
  //  delta: maximum change in likelihood if this SNP is made homozygous or removed
  //  rMEC: reduction in MEC score if we remove this variant altogether
```

I see that HAPCUT2 outputs three columns instead.

Could you define the output format for both the VCF-genotype and hapcut-specific columns?  For HAPCUT it was column 8 and 9 (1-based), and for HACUT2 it appears to be 8 and 9-11 respectively.

**Comment by nh13** [comment]
I forgot to mention, the motivation for parsing the output is to put the data back into VCF format.  Currently I have a tool [HapCutToVcf](https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala) that converts the output of HAPCUT to VCF.  I want to support HAPCUT2 as well.

**Comment by pjedge** [comment]
Hi Nils. Sorry, I'm behind on writing the readme for HapCUT2 but it's coming soon. If it's alright with you I'll link to HapCutToVCF in it, it's sure to be of interest to users.

Field 8 is taken directly from the input VCF file so it depends on the format field of the input. I should probably add the format field of the VCF into the output too. Another issue just occured to me however -- HapCUT2 can be set to correct the genotype if there is strong evidence it is wrong, and in this case it wouldn't match up to the VCF's call in this field anymore (e.g. there could be a phase of '1 1' or '0 0'), and the GQ would be meaningless as well. I wonder if I should even include this field at all (but it's probably important for your purposes).

Field 9 describes the status of the SNV under a discrete SNV pruning method (1 == pruned, 0 == phased; an SNV is pruned if there are equal reads consistent and inconsistent with the phase). This is the SNV pruning method introduced by RefHap with the slight difference that reads are initially assigned to haplotypes using read likelihood in our implementation.

The values in field 10 and field 11 are the log<sub>10</sub> of confidence scores that range from 0.5  (less confident) to 1 (most confident). They're actually bayesian posterior probabilities under some simplifying assumptions. The HapCUT2 manuscript will describe how these scores are obtained but if you want more information I can give it. 

Field 10 represents the confidence that there is not a switch error occuring immediately before the SNV. It is fixed at 0 (confidence 1.0) unless switch error scores are computed using either flag "--split_blocks 1" (compute switch error confidence and automatically split blocks using the value of --split_threshold) or "--error_analysis_mode 1" (compute switch error confidence but leave blocks intact and all SNVs phased for manual pruning later). In general we find this style of post-processing to be mostly useful for improving switch error rates in long-read datasets with high error rates (e.g. a low coverage PacBio dataset)

Field 11 can be thought to represent the confidence that the SNV is not a mismatch (single SNV) error. In general, this confidence score is more universally applicable than field 10.

The default behavior of HapCUT2 is to not split any blocks but to prune individual SNVs ('- -' phasing) for which 10<sup>(field 11)</sup> < 0.8, as these are highly likely to be errors regardless of the experiment and read technology.

**Comment by nh13** [comment]
👍 thanks for the quick response.  

I think it is fine if Hapcut2 corrects the genotype based on phase, as long as there is a way to tell it is corrected like you described (ex. the call is 0/1 but hapcut says 1/1).  I can update the final VCF to produce the hapcut-correct genotype in this case and discard any information (GQ/PL) that are now meaningless (unless HapCut2 gives updated values).

As long as you have a finalized the output format, I can parse it and re-create a BAM just like I have for HapCut.v1.  It looks like field 9 should be added to the FILTER column in the VCF, and fields 10 & 11 should be added to the genotypes FORMAT tags.  Let me know if the format is finalized and I can add support for HapCut.v2 in my `HapCutToVcf` tool.  The motivation for getting back to a VCF is that is how most folks consume variants, and we are in the process of writing tools to assess the output of phased variants in VCF ([see this WIP](https://github.com/fulcrumgenomics/fgbio/pull/72)).

**Comment by nh13** [comment]
@pjedge  my email is `nilshomer + @ + gmail + com` in case we want to take this offline.  Could you shoot me yours if you are comfortable.
